version: '3'

networks:
  datascout-network:

services:

  php:
    build:
      context: ./docker/php
    container_name: datascout-php
    environment:
      APP_ENV: dev
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - '9000:9000'
    restart: always
    networks:
      - datascout-network

  nginx:
    image: nginx:stable-alpine
    container_name: datascout-nginx
    ports:
      - '80:80'
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    depends_on:
      - php
    restart: always
    networks:
      - datascout-network

  database:
    image: mysql:8
    container_name: datascout-database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    networks:
      - datascout-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: datascout-pma
    links:
      - database
    environment:
      PMA_HOST: datascout-database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
    restart: always
    ports:
      - 8081:80
    networks:
      - datascout-network